version: "3.1"
services:
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile 
        container_name: nginx
        ports: 
            - 3000:3000


    api: 
        build: 
            context: .
            dockerfile: Dockerfile 
        container_name: api